# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('P', 'Patient'), ('D', 'Doctor')], max_length=15, null=True),
        ),
    ]
